name: Run miri tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

defaults:
  run:
    working-directory: ./bbqueue

jobs:
  miri:
    name: "miri all the things"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install miri component
        run: rustup component add --toolchain nightly-x86_64-unknown-linux-gnu miri
      #
      # crate
      #
      - name: Miri test bbqueue
        run: ./miri.sh
